
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/renan/.pico-sdk/cmake/v3.29.9/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:39 (project)"
    message: |
      The target system is: PICO -  - cortex-m0plus
      The host system is: Windows - 10.0.22631 - AMD64
...
